name       : python-guessit
version    : 3.4.1
release    : 9
source     :
    - https://github.com/guessit-io/guessit/releases/download/v3.4.1/guessit-3.4.1.tar.gz : e732a5010cdac5ac5d410408146ac804e41380e2c9003722044bb817e8f0b217
homepage   : https://github.com/guessit-io/guessit
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A library for guessing information from video filenames
description: |
    GuessIt is a python library that extracts as much information as possible from a video filename. It has a very powerful matcher that allows to guess properties from a video using its filename only. This matcher works with both movies and tv shows episodes.
builddeps  :
    - pylint
    - pytest-runner # check
    - python-babelfish
    - python-dateutil
    - python-pytest-benchmark # check
    - python-pytest-cov # check
    - python-pytest-mock # check
    - python-rebulk
rundeps    :
    - python-babelfish
    - python-dateutil
    - python-rebulk
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    needs newer pytest
#    %python3_test
