name       : python-guessit
version    : 3.0.3
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/g/guessit/guessit-3.0.3.tar.gz : 590cfaac6adbc65a0297f7b2a44c2accf2cc660eeed6283b43cbad30e65806e0
license    : LGPL-3.0-or-later
component  : programming.python
summary    : a library for guessing information from video filenames
description: |
    GuessIt is a python library that extracts as much information as possible from a video filename.
    
    It has a very powerful matcher that allows to guess properties from a video using its filename only. This matcher works with both movies and tv shows episodes.
builddeps  :
    - pytest-runner
rundeps    :
    - python-babelfish
    - python-dateutil
    - python-rebulk
build      : |
    %python3_setup
install    : |
    %python3_install
