name       : python-guessit
version    : 3.1.1
release    : 7
source     :
    - https://github.com/guessit-io/guessit/archive/3.1.1.tar.gz : dccb66d6d80963382753e9a456a28f8f7da10b9932e96e42bccc74a081cd2e8c
homepage   : https://github.com/guessit-io/guessit
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A library for guessing information from video filenames
description: |
    GuessIt is a python library that extracts as much information as possible from a video filename. It has a very powerful matcher that allows to guess properties from a video using its filename only. This matcher works with both movies and tv shows episodes.
builddeps  :
    - pytest-runner
    - python-babelfish
    - python-dateutil
    - python-pytest-benchmark
    - python-rebulk
rundeps    :
    - python-babelfish
    - python-dateutil
    - python-rebulk
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
